### PR TITLE
Config

### PR DESCRIPTION
**Pull request by Mikulas**
revived https://github.com/nextras/migrations/tree/config

Refactored migration group definition to instance of configurator. 

Added:
- `Nextras\Migrations\Configurations\DefaultConfiguration`
- nette DI options:
  - `configuration` => `class name`
  - `withDummyData` => bool
  - `commands` => [`command name` => `class name`]

Changes:
- `--production` argument was removed and replaced with config `withDummyData` option

### CODE REVIEW

**Comment by hrach** [comment]
I, personally, have an usecase for `--production` option I would like too see to override it in the CLI.

**Comment by Mikulas** [comment]
I believe we had this discussion earlier but I can't find it. Production should be the safest environment and thus should not rely on users remembering to invoke commands with a `--production` argument. It would only matter if first dummy data migration was added later on, but it might be very problematic nevertheless.

Please note I did not remove the dummy data switch. What is your usecase? Isn't it solved by separating configuration for each stage and setting `withDummyData` on for dev but not prod?

**Comment by hrach** [comment]
I realize I'm ok with config settings. I was not suggesting to add `--production` switch, only to ability to switch the behavior :-)

**Comment by Mikulas** [comment]
I'm not very much experienced with writing DI extensions and would appreciate thorough code review of MigrationsExtension. For instance I don't really know if it's better to specify the class names or passing an instance or specifying name of a service.

I believe commands can now (as in this PR) be specified by tagging services with `kdyby.console.command` and by giving FQN to the `commands` dictionary. Would it be appropriate to also add support for `@service.name` syntax? Similarly for the `configuration` option.

**Comment by JanTvrdik** [comment]
Can we finally merge this?

----

> Would it be appropriate to also add support for @service.name syntax? 

Let's implement it once there would be a real-world need.

**Pull request closed without merging**
