### PR TITLE
Run force migrations

### PR DESCRIPTION
**Pull request by petrparolek**
added support for run force migrations.

My motivation: I am working on project in in version 1.x and 2.x, both major versions is in developing

### CODE REVIEW

**Comment by mabar** [comment]
`migrations:reset`?

**Comment by petrparolek** [comment]
in production environment? Bad way

**Comment by mabar** [comment]
Permanently broken migrations integrity? Also bad way.

**Comment by hrach** [comment]
If you have multiple projects, make migrations a shared component/project/dependency. This really breaks integrity and safety provided by nestraš migrations.

**Pull request closed without merging**
